name: Vercel Deployment Success Trigger

on:
  deployment_status:
  workflow_dispatch:

jobs:
  dispatch-custom-event:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to Paranoia8972/Paranoia8972
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Paranoia8972/Paranoia8972/dispatches \
            -d '{"event_type":"vercel-deployment-success"}'
